### ISSUE TITLE
RTSP

### ISSUE THREAD

**Issue by luca-ferrari-roma** [bartbutenaers/node-red-contrib-multipart-stream-encoder#5]
Hi.
Is it possible to use RTSP protocol instead HTTP, using multipart-encoder node?

Kindly regards
Luca

**Comment by bartbutenaers** [comment]
Hi Luca,

No rtsp is a completely other protocol.  If I were you, I should have a look at [this ](https://discourse.nodered.org/t/beta-testing-nodes-for-live-streaming-mp4/)discussion.

Good luck with it!
Bart
